### ISSUE TITLE
link gets generated but when the link is visited, it responds with not found

### ISSUE THREAD

**Issue by mkpgtr** [parthamk/picolink#3]
follow the steps to reproduce the error : 

1. paste your original link
2. click on shorten link.
3. click on the newly generated shortened link or copy & paste it in your address bar 

the server responds with not found

**Comment by parthamk** [comment]
Congratulation!! You have done your first contribution. Please provide more insight about your bug. If possible explain how you will solve it. Don't forget to fork it.

**Comment by praveen8git** [comment]
solution suggestion :
- currently, the original URL is being hashed before saving to DB.
- the hashed URL can't be reversed now, as hashing is a one-way mechanism.
- instead, we can use encryption (e.g. CryptoJS) to encrypt and decrypt the URL.

**Comment by parthamk** [comment]
> * U

You have guessed it write if you want you can fork and fix it then create pull request.

**Comment by mkpgtr** [comment]
> Congratulation!! You have done your first contribution. Please provide more insight about your bug. If possible explain how you will solve it. Don't forget to fork it.

my solution : 
0. original link : https://myfavoriteurl.com/favposts/1
1. generated link : https://picolink.org/oUsOh8oNve
2. catch the slug in the route params & map it to generated link.
3. save this mapping in the db.

now when request comes to : /:slug,

1. find the slug in the db
2. redirect the user to be original link mapped to the slug.

**Comment by parthamk** [comment]
> > Congratulation!! You have done your first contribution. Please provide more insight about your bug. If possible explain how you will solve it. Don't forget to fork it.
> 
> my solution :
> 
> * original link : https://myfavoriteurl.com/favposts/1
> * generated link : https://picolink.org/oUsOh8oNve
> * catch the slug in the route params & map it to generated link.
> * save this mapping in the db.
> 
> now when request comes to : /:slug,
> 
> * find the slug in the db
> * redirect the user to be original link mapped to the slug.
> 
> What a mapping looks like in db :
> 
> * {
>   _id : (...somerandomlongstring),
>   slug : oUsOh8oNve,
>   originalLink : https://myfavoriteurl.com/favposts/1
>   }

I think with this solution the original link will be exposed easily we don't want that. Good try can you suggest something more effective?

**Comment by mkpgtr** [comment]
> > > Congratulation!! You have done your first contribution. Please provide more insight about your bug. If possible explain how you will solve it. Don't forget to fork it.
> > 
> > 
> > my solution :
> > 
> > * original link : https://myfavoriteurl.com/favposts/1
> > * generated link : https://picolink.org/oUsOh8oNve
> > * catch the slug in the route params & map it to generated link.
> > * save this mapping in the db.
> > 
> > now when request comes to : /:slug,
> > 
> > * find the slug in the db
> > * redirect the user to be original link mapped to the slug.
> > 
> > What a mapping looks like in db :
> > 
> > * {
> >   _id : (...somerandomlongstring),
> >   slug : oUsOh8oNve,
> >   originalLink : https://myfavoriteurl.com/favposts/1
> >   }
> 
> I think with this solution the original link will be exposed easily we don't want that. Good try can you suggest something more effective?
the entire point is to shorten urls into readable chunks that can be shared easily.
confidentiality is not an issue here. let me if I am wrong.

**Comment by parthamk** [comment]
This issue is sorted.
