### ISSUE TITLE
add env variables to client(react app)

### ISSUE THREAD

**Issue by mkpgtr** [parthamk/picolink#9]
**Steps to reproduce the behavior:**

- start the application on your local machine.
- check the network tab & see that : axios tries to hit the render endpoint instead of backend running on localhost.
- solve this issue by using React Env variables & dynamically setting the appropriate endpoints in development & production environments.

**Expected behavior**
- axios should hit localhost endpoint when running on local machine.
- axios should hit render endpoint while running on render.

**Comment by parthamk** [comment]
It won't be necessary
